### ISSUE TITLE
Cannot coerce STRING to LocalDate

### ISSUE THREAD

**Issue by senolatac** [neo4j/neo4j-java-driver-spring-boot-starter#40]
My Node looks like:
```
@Getter
@NoArgsConstructor
@Node
public abstract class App
{
    @Id
    @GeneratedValue
    private Long id;

    @Property
    private Long appId;

    @Property
    private LocalDate lastTrackedDate;

    @Relationship(type = AppVisibleOnCountryRelation.TYPE)
    private List<AppVisibleOnCountryRelation> visibleOn = new ArrayList<>();
}
```

And my query looks like:

```
    @Query("MATCH (a:App) - [v:VISIBLE_ON] -> (c:Country{countryCode:$country}) " +
            "WHERE a.appId IN $appId " +
            "RETURN a, a.appId as appId...")
    List<Dto> findVisibilityScores(@Param("appId") List<Long> appId,
                                                                         @Param("country") CountryCode country);
```

But when I try to fetch this query, I get an error like:

```
org.neo4j.driver.exceptions.value.Uncoercible: Cannot coerce STRING to LocalDate
	at org.neo4j.driver.internal.value.ValueAdapter.asLocalDate(ValueAdapter.java:317) ~[neo4j-java-driver-4.1.4.jar:4.1.4-2eaa1f07ee4de9d74adca8aed44133577fbd0d18]
	at org.springframework.data.convert.DefaultConverterBuilder$ConfigurableGenericConverter.convert(DefaultConverterBuilder.java:151) ~[spring-data-commons-2.4.12.jar:2.4.12]
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41) ~[spring-core-5.3.9.jar:5.3.9]
```

any suggestion?

Note: It was working in spring-boot 2.3 but when I try to migrate it to 2.4, it gives error like above.

**Comment by senolatac** [comment]
I wrote a conversion and it solved but I have described it on every LocalDate field. Is there a way to describe it as globally?

```
public class LocalDateConverter implements Neo4jPersistentPropertyConverter<LocalDate>
{
    @Override
    public Value write(LocalDate source)
    {
        if (source == null)
        {
            return null;
        }
        return Values.value(source.toString());
    }

    @Override
    public LocalDate read(Value source)
    {
        if (source.isNull())
        {
            return null;
        }

        return LocalDate.parse(source.asString());
    }
}
```

App class after conversion:

```
@Getter
@NoArgsConstructor
@Node
public abstract class App
{
    @Id
    @GeneratedValue
    private Long id;

    @Property
    private Long appId;

    @ConvertWith(converter = LocalDateConverter.class)
    @Property
    private LocalDate lastTrackedDate;

    @Relationship(type = AppVisibleOnCountryRelation.TYPE)
    private List<AppVisibleOnCountryRelation> visibleOn = new ArrayList<>();
}
```

**Comment by michael-simons** [comment]
That looks like an SDN issue: https://github.com/spring-projects/spring-data-neo4j

I can't transfer it to the project (different org), it would be nice if you reopen it there.

Note that this starter here is *not* needed for Spring Boot 2.4 and higher.
